version: '3.8'
services:
  db:
    image: mysql:latest
    restart: 'no'
    environment:
      MYSQL_DATABASE: ${DB_NAME_TEST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_TEST}
    ports:
      - ${DB_PORTS_TEST}
    expose:
      - ${DB_EXPOSE_PORT_TEST}
    volumes:
      - ${DB_VOLUMES_DIR}
volumes:
  my-db: