version: '3.8'
services:
  db:
    image: mysql:latest
    restart: 'no'
    environment:
      MYSQL_DATABASE: ${DB_NAME_DEV}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_DEV}
    ports:
      - ${DB_PORTS_DEV}
    expose:
      - ${DB_EXPOSE_PORT_DEV}
    volumes:
      - ${DB_VOLUMES_DIR}
volumes:
  my-db: